config/routes.rb
Rails.application.routes.draw do
  root to: 'contacts#home'
  get 'download_pdf', to: "contacts#download_pdf"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :contacts, only: [:new, :create, :home]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   validate: true
  attribute :nickname,  captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "laura@laurabrooks.codes",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def home
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:success] = 'Message sent!'
    else
      flash.now[:error] = 'Could not send message'
      render :home
    end
  end

  def download_pdf
    send_file "#{Rails.root}/public/docs/laura_brooks_resume.pdf", type: "application/pdf", x_sendfile: true
  end


  private

 def contact_params
    params.require(:contact).permit(:contact)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/componants/_about.html.erb
  <div class="container main-wrapper">
    <div class="row">
      <div class="col-11 col-md-5 col-lg-7">
        <div class="container">
          <h5>Hi, my name is</h5>
          <p id="name" class="title-shadow">Laura Brooks</p>
          <h2>Fullstack Developer and Ruby on Rails Engineer</h2>
          <h4> Ruby on Rails | JavaScript | React | HTML | CSS | Ruby | </h4>
          <p>I'm a freelance developer and engineer specializing in minimilistic web design and SEO. If you are looking for good functionality, understated, simple design, and top SEO? Then I've got what you need. Take a look at my projects below and message me for a chat! I will make your website stand out.</p>
        </div>
      </div>
      <div class="col-11 col-md-5 col-lg-5 d-flex">
      <div class="image-fluid">
        <img class="avatar-square"src="<%= image_path 'professional_pic_large_square.jpg' %> "alt="picture of Laura Brooks">
      </div>
    </div>
  </div>

app/views/componants/_footer.html.erb
<div class="footer purple">
    <footer>
      <!-- scroll to top -->
      <p>Website made with ❤️ by Laura Brooks</p>
      <a id="to_Top" href="#one">
        <div class="to-Top"></div>
      </a>
    </footer>
  </div>

app/views/componants/_navbar.html.erb
  <nav>
    <div class="navbar fadeEl">
      <a href="home.html.erb" class="nav-branding"></a>
      <ul class="nav-menu">
        <li class="nav-item"><a class="nav-link fadeEl" id="sec-1" href="#one">About</a></li>
        <li class="nav-item"><a class="nav-link fadeEl-second" id="sec-2" href="#two">Projects</a></li>
        <li class="nav-item"><a class="nav-link fadeEl-third" id="sec-3" href="#three">Contact</a></li>
        <li class="nav-item"><%= link_to "Resume", download_pdf_path, class: "nav-link fadeEl-fourth"%></li>
      </ul>
      <div class="hamburger">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
      </div>
    </div>
  </nav>

app/views/componants/_projects.html.erb
<div class="container main-wrapper">
  <div class="row mt-5">
    <div class="col-12 col-md-4 col-lg-6">
      <a href="https://www.cdsofficialmusic.com" target="_blank"><img src=<%= image_path ('cds.png') %> class=" img-fluid site-image" id="mobile-img" alt="image of cds official music"></a>
    </div>


    <div class="col-12 col-md-8 col-lg-6">

      <div class="site-text">
        <h2 class="title-shadow">CDS Official Music</h3>
        <h4>Role: Fullstack Developer</h4>
        <p>A website designed for CDS Official Music to showcase the talents of the artist Connor D. Steck. I designed the site from start to finish using figma to draw up a prototype before checking with the client for revisions. I implemented one page scrolling with Javascript as well as mobile responsiveness for easy use across devices. I host and manage the site on Heroku and still update the site when needed.</p>
      </div>
      <div class="col-12 col-md-8 col-lg-6">
        <div class="dev-icons">
          <i class="devicon-html5-plain"></i> <i class="devicon-css3-plain"></i> <i class="devicon-rails-plain"></i><i
            class="devicon-nodejs-plain"></i><i class="devicon-ruby-plain"></i>
        </div>
      </div>
    </div>
  </div>

  <div class="splitter"></div>

  <%# CAREAROUND %>
  <div class="row mt-3">
    <div class="col-12 col-md-8 col-lg-7">
      <div class="container">
      <div class="site-text">
          <h2 class="title-shadow">CareAround</h3>
          <h4>Role: Project Manager</h4>
          <p>A mobile application to find your skincare match in Japan. Carearound used google vision and live translation APIs to deliver an application that allows the customer to quicly and easily identify a suitable product for them. My role included researching and implementing the best servcies to use for backend development and making sure the project was delivered by the team fully functional on time. </p>
        </div>
        <div class="col-12 col-md-8 col-lg-7">
          <div class="dev-icons">
            <i class="devicon-html5-plain"></i> <i class="devicon-css3-plain"></i> <i class="devicon-rails-plain"></i><i
              class="devicon-nodejs-plain"></i><i class="devicon-ruby-plain"></i>
          </div>
        </div>
      </div>
    </div>

    <div class="col-6 col-md-2 col-lg-2">
        <a href="https://www.carearound.life" target="_blank"><img src=<%= image_path ('carearound.png') %> class=" img-fluid site-image" alt="image of carearound site"></a>
    </div>
    <div class="col-6 col-md-2 col-lg-2">
       <a href="https://www.carearound.life" target="_blank"><img src=<%= image_path ('ca_jp_products.png') %> class=" img-fluid site-image" alt="image of carearound site"></a>
    </div>

  </div>

  <div class="splitter"></div>

 <%# JEDI %>
  <div class="row mt-5">
    <div class="col-12 col-md-4 col-lg-6">
      <a href="https://jedi-masterclass.onrender.com" target="_blank"><img src=<%= image_path ('jedi.png') %> class=" img-fluid site-image" id="mobile-img" alt="image of jedi master class site"></a>
    </div>

    <div class="col-12 col-md-8 col-lg-6">

      <div class="site-text">
        <h2 class="title-shadow">Jedi Master Class</h3>
        <h4>Role: Project Manager/Backend Developer</h4>
        <p>A web app modeled off of Air BnB where you can book classes with a Jedi or Sith master and hone your skills with the force. As a Jedi or Sith master you can create classes for future padawans to book. My role included managing our team so that all user stories were clearly implemented and that design and functionality was consistant across the app. From a backend perspective I was responsible for creating the booking function and managing the lessons page. </p>
      </div>
      <div class="col-12 col-md-8 col-lg-6">
        <div class="dev-icons">
          <i class="devicon-html5-plain"></i> <i class="devicon-css3-plain"></i> <i class="devicon-rails-plain"></i><i
            class="devicon-nodejs-plain"></i><i class="devicon-ruby-plain"></i>
        </div>
      </div>
    </div>
  </div>

  <div class="splitter"></div>

<%# GIF SEARCHER %>
  <div class="row mt-5">
    <div class="col-12 col-md-8 col-lg-6">
      <div class="site-text">
        <h2 class="title-shadow">Gif Searcher</h3>
          <h4>Role: Fullstack Developer</h4>
          <p>A web app made entirley with React. Used the Giphy API in order to search for the gifs. Made with help from
            LeWagon </p>
      </div>
      <div class="col-12 col-md-8 col-lg-6">
        <div class="dev-icons">
          <i class="devicon-react-original"></i><i class="devicon-html5-plain"></i><i class="devicon-css3-plain"></i>
        </div>
      </div>
    </div>

    <div class="col-12 col-md-4 col-lg-6">
      <a href="https://lhb410.github.io/I-Bequeath-you-with-this-Gif/" target="_blank"><img src=<%= image_path ('react_gif.png') %> class=" img-fluid site-image" alt="image of gif searcher site"></a>
    </div>
  </div>

  <div class="splitter"></div>

  <%# AIR BNB %>

  <div class="row mt-5">
    <div class="col-12 col-md-4 col-lg-6">
      <a href="https://github.com/LHB410/rails-simple-airbnb" target="_blank"><img src=<%= image_path ('airbnb.png') %> class=" img-fluid site-image" id="mobile-img" alt="image of airbnb site"></a>
    </div>

    <div class="col-12 col-md-8 col-lg-6">
      <div class="site-text">
        <h2 class="title-shadow">Simple AirBnB</h3>
          <h4>Role: Fullstack Developer</h4>
          <p>A simple web clone of the website Airbnb. Here you can browse and book a flat to rent. Or as an onwer upload a flat to be rented. Built using Ruby on rails and bootstrap it has a clean and simple design. The Mapbox API is used to fetch maps for the flats based on there addresses. My role was designing the entire wesbite. I designed the back end and front end aspects of the site. I used embedded Ruby to include easy to read functionality within the HTML. </p>
      </div>
      <div class="col-12 col-md-8 col-lg-6">
        <div class="dev-icons">
          <i class="devicon-html5-plain"></i> <i class="devicon-css3-plain"></i> <i class="devicon-rails-plain"></i><i
              class="devicon-ruby-plain"></i>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/_new.html.erb
<div  class="container m-4 fadeEl">
  <div class="row">
    <div class="col-12 col-md-4 col-lg-4">
      <div class="container">
        <div class="form-group mr-4" id="form">
          <%= simple_form_for :contact, url: contacts_path do |f| %>
            <%= f.label :name %></br>
            <%= f.text_field  :name, required: true, class: "form-group contact-form-text-area" %></br>

            <%= f.label :email %></br>
            <%= f.text_field :email, required: true, class: "form-group contact-form-text-area" %></br>

            <%= f.label :message %></br>
            <%= f.text_area :message, rows: 8, cols: 25, required: true, class: "form-group contact-form-text-area",
                  placeholder: "Send me a message"%></br>

            <div class= "d-none">
              <%= f.label :nickname %>
              <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
            </div>

            <%= f.submit 'Send Message', class: 'button' %>
            <div class="loader">
              <div class="check">
                <span class="check-one"></span>
                <span class="check-two"></span>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/create.html.erb
<div class="container">
  <h1>Contact Form</h1>

  <h3>Thank you for your message!</h3>
</div>

app/views/contacts/home.html.erb
<%= render 'componants/navbar' %>
<div class="side-style">
  <ul class=side-list-style>
    <li><a  href="https://www.linkedin.com/in/laura-h-brooks" target="_blank"><i id="social-icon" class="fab fa-linkedin fadeEl-second"></i></a></li>

    <li><a href="https://twitter.com/LauraBrooks0" target="_blank"><i id="social-icon" class="fab fa-twitter-square fadeEl-third"></i></a></li>

    <li><a href="https://www.github.com/LHB410" target="_blank"><i id="social-icon" class="fa-brands fa-github fadeEl-fourth"></i></a></li>
  </ul>
</div>
<%# ABOUT %>
<div class="salmon">
  <div id="one" class="default first item fadeEl-second">
    <%= render 'componants/about' %>
  </div>
</div>



<%# PROJECTS %>
<div class="green">
  <div id="two" class="item fadeEl-third">
    <%= render 'componants/projects' %>
  </div>
</div>


</div>

<%# CONTACT FORM %>
<div class="gold">
  <div id="three" class="item">
    <%= render 'new' %>
  </div>
</div>

<%# FOOTER %>
<div class="purple fadeEl">
  <%= render 'componants/footer' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Laura Brooks | Web Development Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.14.0/devicon.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="container">
      <br>
      <% flash.each do |key, message| %>
        <p class="alert alert-<%= key %>"><%= message %></p>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>